require('settings')
require('packer-config')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('mappings')
require('colorschemes-config.tab')
require('colorschemes-config.status')
require('nvim-tree-config')
require("nvim-tree-config.treesitter")

